export type EmojiPaletteItem = {
  emoji: string;
  label: string;
  description: string;
};

/** IrodoriTTS `gradio_emoji_palette.py` と同じ並び・意味。 */
export const EMOJI_PALETTE_ITEMS: EmojiPaletteItem[] = [
  { emoji: "👂", label: "囁き", description: "耳元の音" },
  { emoji: "😮‍💨", label: "吐息", description: "溜息、寝息" },
  { emoji: "⏸️", label: "間", description: "沈黙" },
  { emoji: "🤭", label: "笑い", description: "くすくす、含み笑い" },
  { emoji: "🥵", label: "喘ぎ", description: "うめき声、唸り声" },
  { emoji: "📢", label: "エコー", description: "リバーブ" },
  { emoji: "😏", label: "からかう", description: "甘えるように" },
  { emoji: "🥺", label: "震え声", description: "自信なさげに" },
  { emoji: "🌬️", label: "息切れ", description: "荒い息遣い、呼吸音" },
  { emoji: "😮", label: "息をのむ", description: "Gasp" },
  { emoji: "👅", label: "舐める音", description: "咀嚼音、水音" },
  { emoji: "💋", label: "リップノイズ", description: "Lip smack" },
  { emoji: "🫶", label: "優しく", description: "Tenderly" },
  { emoji: "😭", label: "泣き声", description: "嗚咽、悲しみ" },
  { emoji: "😱", label: "悲鳴", description: "叫び、絶叫" },
  { emoji: "😪", label: "眠そう", description: "気だるげに" },
  { emoji: "😴", label: "寝言", description: "いびき" },
  { emoji: "⏩", label: "早口", description: "一気に、急いで" },
  { emoji: "📞", label: "電話越し", description: "スピーカー越し" },
  { emoji: "🐢", label: "ゆっくり", description: "Slowly" },
  { emoji: "🥤", label: "飲み込む", description: "唾を飲む音" },
  { emoji: "🤧", label: "咳・鼻", description: "咳き込み、鼻すすり" },
  { emoji: "😒", label: "舌打ち", description: "Tutting" },
  { emoji: "😰", label: "慌てる", description: "動揺、緊張、どもり" },
  { emoji: "😆", label: "喜び", description: "嬉しそうに" },
  { emoji: "💥", label: "勢いよく", description: "力強い勢い" },
  { emoji: "😠", label: "怒り", description: "不満げ、拗ねる" },
  { emoji: "😲", label: "驚き", description: "感嘆" },
  { emoji: "🥱", label: "あくび", description: "Yawn" },
  { emoji: "😖", label: "苦しげ", description: "Agonizingly" },
  { emoji: "😟", label: "心配", description: "不安そうに" },
  { emoji: "🫣", label: "照れ", description: "恥ずかしそうに" },
  { emoji: "🙄", label: "呆れ", description: "Exasperatedly" },
  { emoji: "😊", label: "楽しげ", description: "嬉しそうに" },
  { emoji: "😎", label: "得意げ", description: "自信ありげに" },
  { emoji: "👌", label: "相槌", description: "頷く音" },
  { emoji: "🙏", label: "懇願", description: "お願いするように" },
  { emoji: "🥴", label: "酔う", description: "Drunkenly" },
  { emoji: "🎵", label: "鼻歌", description: "Humming" },
  { emoji: "🤐", label: "口を塞ぐ", description: "Muffled" },
  { emoji: "😌", label: "安堵", description: "満足げに" },
  { emoji: "🤔", label: "疑問", description: "Questioning" },
  { emoji: "💪", label: "力強く", description: "力を込めて" },
  { emoji: "👃", label: "嗅ぐ音", description: "匂いを嗅ぐ音" },
  { emoji: "📖", label: "朗読", description: "ナレーション" },
];
